/** The aircraft types pre-defined in Shirley. */
export const AircraftCodes = [
  "a103ulac",
  "a333",
  "ask21",
  "b58",
  "c90b",
  "a250vtol",
  "b738",
  "c750",
  "c172sp",
  "c172spG1000",
  "c172spFloats",
  "sf50",
  "sr22",
  "da42ng",
  "f14",
  "f4",
  "l1t",
  "md82",
  "pa18",
  "r22",
  "r22Floats",
  "s76c",
  "l5",
  "rv10",
  "genericSingleFixedPiston",
  "genericSingleComplexPiston",
  "genericTwinPiston",
  "genericSingleComplexTurbine",
  "genericTwinTurbine",
  "genericSingleJet",
  "genericTwinJet",
  "genericSinglePistonHelicopter",
  "genericSingleTurbineHelicopter",
  "genericTwinTurbineHelicopter",
  "other",
] as const;

/** The code of an aircraft type supported by Shirley. */
export type AircraftCode = (typeof AircraftCodes)[number];
